alter table QUEMEPONGO_GUARDARROPA alter column USUARIO_ID rename to USUARIO_ID__U29304 ^
alter table QUEMEPONGO_GUARDARROPA alter column USUARIO_ID__U29304 set null ;
drop index IDX_QUEMEPONGO_GUARDARROPA_ON_USUARIO ;
alter table QUEMEPONGO_GUARDARROPA drop constraint FK_QUEMEPONGO_GUARDARROPA_ON_USUARIO ;
