alter table QUEMEPONGO_EVENTO add constraint FK_QUEMEPONGO_EVENTO_ON_GUARDARROPA foreign key (GUARDARROPA_ID) references QUEMEPONGO_GUARDARROPA(ID);
create index IDX_QUEMEPONGO_EVENTO_ON_GUARDARROPA on QUEMEPONGO_EVENTO (GUARDARROPA_ID);
