alter table QUEMEPONGO_GUARDARROPA add constraint FK_QUEMEPONGO_GUARDARROPA_ON_USUARIO foreign key (USUARIO_ID) references SEC_USER(ID);
create index IDX_QUEMEPONGO_GUARDARROPA_ON_USUARIO on QUEMEPONGO_GUARDARROPA (USUARIO_ID);
