alter table QUEMEPONGO_TIPO_PRENDA add constraint FK_QUEMEPONGO_TIPO_PRENDA_ON_CATEGORIA foreign key (CATEGORIA_ID) references QUEMEPONGO_CATEGORIA(ID);
create unique index IDX_QUEMEPONGO_TIPO_PRENDA_UNIQ_NOMBRE on QUEMEPONGO_TIPO_PRENDA (NOMBRE) ;
create index IDX_QUEMEPONGO_TIPO_PRENDA_ON_CATEGORIA on QUEMEPONGO_TIPO_PRENDA (CATEGORIA_ID);
